# Generated by Django 5.2.1 on 2025-06-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0002_user_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='fabricante',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
