# Generated by Django 5.2.1 on 2025-06-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0003_instrumento_fabricante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumento',
            old_name='fabricante',
            new_name='folio',
        ),
    ]
